title : repentsinner

author :
  name : Ritchie Argue
  email : github@repentsinner.org
  github : repentsinner
  
theme: jekyll-theme-minimal

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-seo-tag
